### ISSUE TITLE
about result

### ISSUE THREAD

**Issue by zhoudreames** [mrvollger/assembly_workflows#3]
in final output, there are some files such as test.SDs.bed, test.lowid.bed and test.enriched.bed. What do these documents means？ thanks~

**Comment by mrvollger** [comment]
*  `test.enriched.bed` this is an unused output so can be ignored
* `test.SDs.bed` this is the file with the SDs
*  `test.SDs.lowid.bed` these are SDs identified with SEDEF that do not meet filters on length (1kbp) and identity (90%)

You can find columns descriptions for the SD bed files on the browser:
https://genome.ucsc.edu/cgi-bin/hgTables?db=hub_3267197_GCA_009914755.4&hgta_group=varRep&hgta_track=hub_3267197_sedefSegDups&hgta_table=hub_3267197_sedefSegDups&hgta_doSchema=describe+table+schema
